export default [
  {
    username: 'bryan46',
    firstName: 'Cameron',
    lastName: 'Baker',
    email: 'wilsonjames@mason-jones.com',
    birthDate: '2002-09-25',
    basicSalary: 86960.32,
    status: 'Inactive',
    group: 'Marketing',
    description: '2021-05-23',
  },
  {
    username: 'reginaldwilliams',
    firstName: 'Krystal',
    lastName: 'Hernandez',
    email: 'meltongarrett@reynolds.net',
    birthDate: '2001-01-26',
    basicSalary: 73674.87,
    status: 'Inactive',
    group: 'Engineering',
    description: '2020-06-23',
  },
  {
    username: 'rachel05',
    firstName: 'John',
    lastName: 'Hicks',
    email: 'taylorthomas@gmail.com',
    birthDate: '1995-06-13',
    basicSalary: 100363.4,
    status: 'Inactive',
    group: 'Sales',
    description: '2022-10-31',
  },
  {
    username: 'baileyvanessa',
    firstName: 'Manuel',
    lastName: 'Bryant',
    email: 'qstout@hotmail.com',
    birthDate: '1960-09-17',
    basicSalary: 36917.99,
    status: 'Active',
    group: 'Engineering',
    description: '2023-05-08',
  },
  {
    username: 'cabrerabrittany',
    firstName: 'Jeremy',
    lastName: 'Robbins',
    email: 'perkinsdanielle@hanna.com',
    birthDate: '1964-09-25',
    basicSalary: 36372.91,
    status: 'On Leave',
    group: 'Engineering',
    description: '2024-05-04',
  },
  {
    username: 'michaelthomas',
    firstName: 'Christina',
    lastName: 'Spence',
    email: 'lynchpatrick@yahoo.com',
    birthDate: '1970-10-12',
    basicSalary: 111921.42,
    status: 'Active',
    group: 'Engineering',
    description: '2024-02-23',
  },
  {
    username: 'mario43',
    firstName: 'Scott',
    lastName: 'James',
    email: 'bethhood@smith.com',
    birthDate: '1977-11-27',
    basicSalary: 93301.18,
    status: 'On Leave',
    group: 'HR',
    description: '2021-05-29',
  },
  {
    username: 'qcarter',
    firstName: 'Jeffrey',
    lastName: 'Dominguez',
    email: 'angelasmith@hotmail.com',
    birthDate: '1964-05-23',
    basicSalary: 92077.7,
    status: 'On Leave',
    group: 'Marketing',
    description: '2022-04-13',
  },
  {
    username: 'courtney87',
    firstName: 'Eduardo',
    lastName: 'Odonnell',
    email: 'pagestephanie@cook-blackburn.com',
    birthDate: '1992-08-29',
    basicSalary: 101345.41,
    status: 'Active',
    group: 'Sales',
    description: '2020-01-03',
  },
  {
    username: 'holderandrew',
    firstName: 'Aaron',
    lastName: 'Evans',
    email: 'hsandoval@yahoo.com',
    birthDate: '1995-11-21',
    basicSalary: 115577.59,
    status: 'On Leave',
    group: 'HR',
    description: '2022-11-13',
  },
  {
    username: 'matthew03',
    firstName: 'Tracie',
    lastName: 'Martinez',
    email: 'tamaralopez@hotmail.com',
    birthDate: '1977-07-03',
    basicSalary: 87419.03,
    status: 'Active',
    group: 'Engineering',
    description: '2021-03-01',
  },
  {
    username: 'omar48',
    firstName: 'Tiffany',
    lastName: 'Johnson',
    email: 'lcompton@yahoo.com',
    birthDate: '1984-04-15',
    basicSalary: 39326.15,
    status: 'Inactive',
    group: 'Finance',
    description: '2022-08-11',
  },
  {
    username: 'robert72',
    firstName: 'Tyler',
    lastName: 'King',
    email: 'austin51@reid.com',
    birthDate: '1973-06-03',
    basicSalary: 58872.9,
    status: 'On Leave',
    group: 'Sales',
    description: '2022-03-31',
  },
  {
    username: 'colemanmary',
    firstName: 'Lisa',
    lastName: 'Wood',
    email: 'xanderson@hotmail.com',
    birthDate: '1978-05-15',
    basicSalary: 80026.85,
    status: 'Inactive',
    group: 'Marketing',
    description: '2024-03-27',
  },
  {
    username: 'larsenmary',
    firstName: 'Zachary',
    lastName: 'Miller',
    email: 'cummingsgene@yahoo.com',
    birthDate: '1965-12-06',
    basicSalary: 114982.52,
    status: 'Inactive',
    group: 'Finance',
    description: '2020-08-19',
  },
  {
    username: 'veronica24',
    firstName: 'Justin',
    lastName: 'Mckenzie',
    email: 'robertsonbrooke@hotmail.com',
    birthDate: '1968-06-07',
    basicSalary: 44445.0,
    status: 'Active',
    group: 'Sales',
    description: '2021-03-06',
  },
  {
    username: 'ichan',
    firstName: 'Ashley',
    lastName: 'Watson',
    email: 'jonesmarissa@gmail.com',
    birthDate: '1959-07-04',
    basicSalary: 67142.1,
    status: 'Active',
    group: 'Engineering',
    description: '2020-06-20',
  },
  {
    username: 'pjohnson',
    firstName: 'Autumn',
    lastName: 'Barton',
    email: 'moniquedelgado@harris-jones.net',
    birthDate: '1966-09-17',
    basicSalary: 67416.19,
    status: 'On Leave',
    group: 'Sales',
    description: '2022-08-14',
  },
  {
    username: 'richardpamela',
    firstName: 'Charles',
    lastName: 'Campos',
    email: 'hlogan@wallace-wilcox.info',
    birthDate: '1972-09-04',
    basicSalary: 117069.72,
    status: 'Inactive',
    group: 'Engineering',
    description: '2021-02-23',
  },
  {
    username: 'oliverchristina',
    firstName: 'Kevin',
    lastName: 'Curry',
    email: 'ashley28@gmail.com',
    birthDate: '1975-05-05',
    basicSalary: 32129.03,
    status: 'On Leave',
    group: 'Finance',
    description: '2021-12-09',
  },
  {
    username: 'curryjessica',
    firstName: 'Rebecca',
    lastName: 'Barton',
    email: 'heather98@french-harrison.com',
    birthDate: '1960-05-08',
    basicSalary: 34367.9,
    status: 'On Leave',
    group: 'HR',
    description: '2020-10-28',
  },
  {
    username: 'hoffmanandrew',
    firstName: 'Brent',
    lastName: 'Lee',
    email: 'uhumphrey@wong.com',
    birthDate: '1965-08-22',
    basicSalary: 96936.73,
    status: 'Inactive',
    group: 'Sales',
    description: '2021-05-13',
  },
  {
    username: 'jasoncuevas',
    firstName: 'Melanie',
    lastName: 'Kelly',
    email: 'crystalrussell@reynolds.org',
    birthDate: '1975-08-09',
    basicSalary: 71334.7,
    status: 'On Leave',
    group: 'Finance',
    description: '2021-07-24',
  },
  {
    username: 'christopher25',
    firstName: 'Christopher',
    lastName: 'Aguilar',
    email: 'shane88@barnett.com',
    birthDate: '1973-04-18',
    basicSalary: 99171.98,
    status: 'Active',
    group: 'Finance',
    description: '2021-09-07',
  },
  {
    username: 'fjackson',
    firstName: 'Adrian',
    lastName: 'Jenkins',
    email: 'teresachavez@glenn-smith.net',
    birthDate: '1963-07-23',
    basicSalary: 51787.42,
    status: 'On Leave',
    group: 'Sales',
    description: '2022-05-30',
  },
  {
    username: 'melissaaustin',
    firstName: 'Greg',
    lastName: 'Coleman',
    email: 'barbaravillegas@duffy.info',
    birthDate: '1972-10-20',
    basicSalary: 108885.3,
    status: 'Inactive',
    group: 'HR',
    description: '2021-07-10',
  },
  {
    username: 'reginaldmoore',
    firstName: 'Cheryl',
    lastName: 'Sanders',
    email: 'jmontoya@campos.com',
    birthDate: '1971-04-05',
    basicSalary: 114090.15,
    status: 'On Leave',
    group: 'Engineering',
    description: '2023-08-13',
  },
  {
    username: 'shanesmith',
    firstName: 'Wendy',
    lastName: 'Friedman',
    email: 'imyers@yahoo.com',
    birthDate: '1978-07-16',
    basicSalary: 85325.4,
    status: 'On Leave',
    group: 'Engineering',
    description: '2022-01-03',
  },
  {
    username: 'lewiselizabeth',
    firstName: 'Kayla',
    lastName: 'Blair',
    email: 'briansnow@yahoo.com',
    birthDate: '1973-05-18',
    basicSalary: 114991.3,
    status: 'Inactive',
    group: 'Marketing',
    description: '2021-08-11',
  },
  {
    username: 'lindalee',
    firstName: 'Amanda',
    lastName: 'Church',
    email: 'hcook@yahoo.com',
    birthDate: '1976-01-04',
    basicSalary: 90759.99,
    status: 'Active',
    group: 'Finance',
    description: '2021-12-06',
  },
  {
    username: 'hernandezdeanna',
    firstName: 'Madeline',
    lastName: 'Garcia',
    email: 'tscott@hotmail.com',
    birthDate: '1980-02-03',
    basicSalary: 75768.88,
    status: 'Active',
    group: 'HR',
    description: '2023-03-14',
  },
  {
    username: 'erin04',
    firstName: 'Angela',
    lastName: 'Robertson',
    email: 'youngkaren@gmail.com',
    birthDate: '1985-09-03',
    basicSalary: 68729.42,
    status: 'On Leave',
    group: 'Sales',
    description: '2024-05-18',
  },
  {
    username: 'gail76',
    firstName: 'Daniel',
    lastName: 'Lawrence',
    email: 'joannafletcher@daniel-king.com',
    birthDate: '1976-05-11',
    basicSalary: 96121.27,
    status: 'Active',
    group: 'Sales',
    description: '2021-02-19',
  },
  {
    username: 'steve84',
    firstName: 'Patty',
    lastName: 'Jones',
    email: 'billyrivera@hotmail.com',
    birthDate: '1967-05-20',
    basicSalary: 112940.59,
    status: 'Inactive',
    group: 'Marketing',
    description: '2022-12-13',
  },
  {
    username: 'fallen',
    firstName: 'Brooke',
    lastName: 'Harris',
    email: 'robinsheppard@clark.biz',
    birthDate: '1998-10-21',
    basicSalary: 55419.65,
    status: 'Active',
    group: 'Sales',
    description: '2020-06-02',
  },
  {
    username: 'wnorris',
    firstName: 'Andrew',
    lastName: 'Wilson',
    email: 'christopher30@stone-gonzalez.com',
    birthDate: '1971-05-07',
    basicSalary: 54817.45,
    status: 'Inactive',
    group: 'Marketing',
    description: '2020-03-22',
  },
  {
    username: 'mirandajones',
    firstName: 'Wendy',
    lastName: 'Patterson',
    email: 'josephle@hotmail.com',
    birthDate: '1977-06-24',
    basicSalary: 102527.81,
    status: 'Active',
    group: 'Marketing',
    description: '2023-08-06',
  },
  {
    username: 'monicaadams',
    firstName: 'Carla',
    lastName: 'Anderson',
    email: 'hayesjennifer@palmer.org',
    birthDate: '1995-03-23',
    basicSalary: 117138.22,
    status: 'On Leave',
    group: 'Marketing',
    description: '2022-09-15',
  },
  {
    username: 'eric63',
    firstName: 'James',
    lastName: 'Rowland',
    email: 'brownerica@hotmail.com',
    birthDate: '1982-05-28',
    basicSalary: 59329.94,
    status: 'On Leave',
    group: 'Engineering',
    description: '2023-11-21',
  },
  {
    username: 'renee86',
    firstName: 'Daniel',
    lastName: 'Lee',
    email: 'jennifercisneros@gmail.com',
    birthDate: '1985-07-01',
    basicSalary: 33437.01,
    status: 'On Leave',
    group: 'Engineering',
    description: '2021-07-29',
  },
  {
    username: 'jimenezmallory',
    firstName: 'Teresa',
    lastName: 'Moran',
    email: 'sgarcia@cochran-hamilton.org',
    birthDate: '1980-06-24',
    basicSalary: 95014.36,
    status: 'Inactive',
    group: 'HR',
    description: '2022-07-06',
  },
  {
    username: 'marcus03',
    firstName: 'Deborah',
    lastName: 'Anderson',
    email: 'tylerkim@yahoo.com',
    birthDate: '1969-10-20',
    basicSalary: 38849.4,
    status: 'Active',
    group: 'Engineering',
    description: '2020-07-18',
  },
  {
    username: 'averyjared',
    firstName: 'Gary',
    lastName: 'Green',
    email: 'bwalters@washington-wilson.info',
    birthDate: '1967-01-01',
    basicSalary: 90161.16,
    status: 'Active',
    group: 'Marketing',
    description: '2022-11-28',
  },
  {
    username: 'melanie71',
    firstName: 'Rickey',
    lastName: 'Williams',
    email: 'davisrebecca@hotmail.com',
    birthDate: '1960-10-17',
    basicSalary: 111319.89,
    status: 'On Leave',
    group: 'Finance',
    description: '2020-02-24',
  },
  {
    username: 'jason96',
    firstName: 'Heather',
    lastName: 'Perez',
    email: 'wdorsey@yahoo.com',
    birthDate: '1975-11-23',
    basicSalary: 41734.42,
    status: 'On Leave',
    group: 'HR',
    description: '2024-01-15',
  },
  {
    username: 'ruizchristopher',
    firstName: 'Melissa',
    lastName: 'Sanchez',
    email: 'gene62@cuevas-wallace.biz',
    birthDate: '1963-03-02',
    basicSalary: 105129.15,
    status: 'On Leave',
    group: 'Sales',
    description: '2020-08-09',
  },
  {
    username: 'bfreeman',
    firstName: 'Jeffrey',
    lastName: 'Fitzgerald',
    email: 'jennifer22@hotmail.com',
    birthDate: '1974-01-18',
    basicSalary: 51444.52,
    status: 'Inactive',
    group: 'Finance',
    description: '2024-05-05',
  },
  {
    username: 'adkinsaudrey',
    firstName: 'Scott',
    lastName: 'Davis',
    email: 'olee@cooper-patel.com',
    birthDate: '1983-12-09',
    basicSalary: 61957.14,
    status: 'On Leave',
    group: 'Marketing',
    description: '2021-11-05',
  },
  {
    username: 'paula89',
    firstName: 'Vanessa',
    lastName: 'Nichols',
    email: 'don45@payne.biz',
    birthDate: '1979-08-17',
    basicSalary: 50658.07,
    status: 'On Leave',
    group: 'Marketing',
    description: '2021-12-04',
  },
  {
    username: 'mary99',
    firstName: 'Phillip',
    lastName: 'Chase',
    email: 'deckeralexandra@gmail.com',
    birthDate: '1970-05-02',
    basicSalary: 80082.71,
    status: 'Active',
    group: 'Engineering',
    description: '2022-08-02',
  },
  {
    username: 'andersontyler',
    firstName: 'Alice',
    lastName: 'Irwin',
    email: 'jefferyjones@hotmail.com',
    birthDate: '1960-05-14',
    basicSalary: 60082.49,
    status: 'Inactive',
    group: 'Engineering',
    description: '2023-09-19',
  },
  {
    username: 'cooleyteresa',
    firstName: 'Lori',
    lastName: 'Mitchell',
    email: 'connorcooper@williams.org',
    birthDate: '1976-12-15',
    basicSalary: 111517.71,
    status: 'On Leave',
    group: 'Engineering',
    description: '2023-05-31',
  },
  {
    username: 'ajackson',
    firstName: 'Tina',
    lastName: 'Suarez',
    email: 'shebert@wells.org',
    birthDate: '1971-09-28',
    basicSalary: 88145.09,
    status: 'Inactive',
    group: 'HR',
    description: '2021-09-15',
  },
  {
    username: 'fletchernicholas',
    firstName: 'Robert',
    lastName: 'Jacobs',
    email: 'ddavis@stone-smith.biz',
    birthDate: '2004-07-22',
    basicSalary: 113648.4,
    status: 'On Leave',
    group: 'HR',
    description: '2023-08-14',
  },
  {
    username: 'tonigray',
    firstName: 'Roberto',
    lastName: 'Farmer',
    email: 'bishoptodd@yahoo.com',
    birthDate: '2002-11-24',
    basicSalary: 92106.52,
    status: 'Inactive',
    group: 'Marketing',
    description: '2021-06-05',
  },
  {
    username: 'sharon19',
    firstName: 'Antonio',
    lastName: 'Alvarez',
    email: 'baileyjoseph@hotmail.com',
    birthDate: '1995-01-13',
    basicSalary: 90097.77,
    status: 'On Leave',
    group: 'Engineering',
    description: '2023-06-29',
  },
  {
    username: 'johnstonspencer',
    firstName: 'James',
    lastName: 'Watson',
    email: 'camerongibson@watkins.biz',
    birthDate: '1982-10-26',
    basicSalary: 82963.51,
    status: 'On Leave',
    group: 'Marketing',
    description: '2020-07-16',
  },
  {
    username: 'leslie21',
    firstName: 'Stephen',
    lastName: 'Thomas',
    email: 'ahill@hotmail.com',
    birthDate: '1963-01-30',
    basicSalary: 70316.11,
    status: 'On Leave',
    group: 'HR',
    description: '2023-07-23',
  },
  {
    username: 'meyerlarry',
    firstName: 'Jennifer',
    lastName: 'Green',
    email: 'mward@gmail.com',
    birthDate: '1967-11-16',
    basicSalary: 108552.42,
    status: 'Inactive',
    group: 'Sales',
    description: '2021-08-05',
  },
  {
    username: 'ywashington',
    firstName: 'Anna',
    lastName: 'Davis',
    email: 'ljones@hotmail.com',
    birthDate: '2003-03-28',
    basicSalary: 118371.18,
    status: 'Inactive',
    group: 'Sales',
    description: '2024-05-08',
  },
  {
    username: 'mathewswanda',
    firstName: 'James',
    lastName: 'Hernandez',
    email: 'ishelton@huynh.biz',
    birthDate: '1967-04-08',
    basicSalary: 109458.67,
    status: 'Inactive',
    group: 'HR',
    description: '2023-06-27',
  },
  {
    username: 'triciacrawford',
    firstName: 'Kimberly',
    lastName: 'Holmes',
    email: 'moralesann@yahoo.com',
    birthDate: '1981-12-04',
    basicSalary: 40444.83,
    status: 'Inactive',
    group: 'Sales',
    description: '2020-01-21',
  },
  {
    username: 'chavezandrew',
    firstName: 'Sharon',
    lastName: 'Hernandez',
    email: 'dustin17@morales.com',
    birthDate: '1977-06-10',
    basicSalary: 83365.86,
    status: 'On Leave',
    group: 'Marketing',
    description: '2023-11-06',
  },
  {
    username: 'yperry',
    firstName: 'Brenda',
    lastName: 'Miller',
    email: 'sarah38@colon-adams.com',
    birthDate: '1988-09-09',
    basicSalary: 108331.8,
    status: 'Active',
    group: 'Sales',
    description: '2022-11-08',
  },
  {
    username: 'scott44',
    firstName: 'Timothy',
    lastName: 'Bailey',
    email: 'eatonkaren@murphy-riggs.com',
    birthDate: '2002-02-24',
    basicSalary: 33353.44,
    status: 'Active',
    group: 'Marketing',
    description: '2023-03-18',
  },
  {
    username: 'rachel22',
    firstName: 'Zachary',
    lastName: 'Byrd',
    email: 'vmorris@hotmail.com',
    birthDate: '1970-01-17',
    basicSalary: 66232.53,
    status: 'On Leave',
    group: 'HR',
    description: '2023-05-30',
  },
  {
    username: 'tricia36',
    firstName: 'John',
    lastName: 'Kelly',
    email: 'bradleyfuller@wiggins.com',
    birthDate: '1985-05-08',
    basicSalary: 65895.69,
    status: 'On Leave',
    group: 'HR',
    description: '2021-01-21',
  },
  {
    username: 'gouldbrenda',
    firstName: 'Carly',
    lastName: 'Carter',
    email: 'jeffreypowell@gmail.com',
    birthDate: '1983-02-02',
    basicSalary: 33037.66,
    status: 'On Leave',
    group: 'Engineering',
    description: '2023-02-05',
  },
  {
    username: 'gbrewer',
    firstName: 'Alexis',
    lastName: 'Bailey',
    email: 'erose@yahoo.com',
    birthDate: '1979-09-16',
    basicSalary: 60228.98,
    status: 'Active',
    group: 'Marketing',
    description: '2023-07-06',
  },
  {
    username: 'joseph92',
    firstName: 'Michelle',
    lastName: 'Moore',
    email: 'obennett@rivera.com',
    birthDate: '2001-10-28',
    basicSalary: 86438.43,
    status: 'Inactive',
    group: 'Finance',
    description: '2023-08-04',
  },
  {
    username: 'maryross',
    firstName: 'Tracy',
    lastName: 'Barton',
    email: 'angela35@gmail.com',
    birthDate: '1998-04-10',
    basicSalary: 79387.08,
    status: 'Inactive',
    group: 'Engineering',
    description: '2022-12-06',
  },
  {
    username: 'johnwhite',
    firstName: 'Angela',
    lastName: 'Simmons',
    email: 'keith95@allen-mclaughlin.biz',
    birthDate: '1966-12-17',
    basicSalary: 99680.52,
    status: 'Active',
    group: 'Finance',
    description: '2022-08-26',
  },
  {
    username: 'lindsey22',
    firstName: 'Audrey',
    lastName: 'Garcia',
    email: 'scottbrian@yahoo.com',
    birthDate: '1993-08-12',
    basicSalary: 102525.87,
    status: 'On Leave',
    group: 'Finance',
    description: '2024-02-20',
  },
  {
    username: 'wwest',
    firstName: 'Jordan',
    lastName: 'James',
    email: 'zlopez@christian.info',
    birthDate: '1977-05-08',
    basicSalary: 59498.51,
    status: 'Active',
    group: 'Finance',
    description: '2023-12-14',
  },
  {
    username: 'nicholasschneider',
    firstName: 'Scott',
    lastName: 'Johnson',
    email: 'patriciakaufman@yahoo.com',
    birthDate: '1991-05-24',
    basicSalary: 62017.35,
    status: 'On Leave',
    group: 'Engineering',
    description: '2020-04-25',
  },
  {
    username: 'yperry',
    firstName: 'Brenda',
    lastName: 'Marshall',
    email: 'eric70@yahoo.com',
    birthDate: '1993-02-09',
    basicSalary: 110037.5,
    status: 'On Leave',
    group: 'Finance',
    description: '2021-02-09',
  },
  {
    username: 'thomaszhang',
    firstName: 'Manuel',
    lastName: 'Campbell',
    email: 'kcole@gmail.com',
    birthDate: '1971-01-12',
    basicSalary: 35013.66,
    status: 'On Leave',
    group: 'HR',
    description: '2023-04-30',
  },
  {
    username: 'rodriguezbruce',
    firstName: 'Jennifer',
    lastName: 'Smith',
    email: 'deborahfriedman@sandoval-jones.org',
    birthDate: '1985-10-05',
    basicSalary: 105868.85,
    status: 'Inactive',
    group: 'Finance',
    description: '2023-12-10',
  },
  {
    username: 'lisaguerra',
    firstName: 'John',
    lastName: 'Klein',
    email: 'robert16@gentry.net',
    birthDate: '1979-08-11',
    basicSalary: 53511.76,
    status: 'Active',
    group: 'Marketing',
    description: '2020-09-16',
  },
  {
    username: 'mrivera',
    firstName: 'David',
    lastName: 'Castro',
    email: 'todd12@simmons.com',
    birthDate: '2000-06-02',
    basicSalary: 61910.94,
    status: 'Inactive',
    group: 'HR',
    description: '2023-06-16',
  },
  {
    username: 'nancy96',
    firstName: 'Claudia',
    lastName: 'Mitchell',
    email: 'stacy48@yahoo.com',
    birthDate: '1971-11-09',
    basicSalary: 46727.64,
    status: 'Inactive',
    group: 'Sales',
    description: '2024-01-07',
  },
  {
    username: 'sparksfrederick',
    firstName: 'Christina',
    lastName: 'Rivas',
    email: 'amy51@hotmail.com',
    birthDate: '1968-01-27',
    basicSalary: 52461.13,
    status: 'Active',
    group: 'Sales',
    description: '2022-11-01',
  },
  {
    username: 'taylorlopez',
    firstName: 'Emily',
    lastName: 'Lewis',
    email: 'hatfieldsteven@ramos-campbell.com',
    birthDate: '1983-05-19',
    basicSalary: 97489.13,
    status: 'On Leave',
    group: 'Engineering',
    description: '2024-01-10',
  },
  {
    username: 'sarah00',
    firstName: 'Amanda',
    lastName: 'Johnson',
    email: 'glenn84@delgado-guerrero.org',
    birthDate: '1982-01-13',
    basicSalary: 75769.26,
    status: 'Active',
    group: 'Engineering',
    description: '2020-12-11',
  },
  {
    username: 'veronicabriggs',
    firstName: 'Joseph',
    lastName: 'Robinson',
    email: 'danderson@smith.biz',
    birthDate: '1960-06-19',
    basicSalary: 87945.42,
    status: 'On Leave',
    group: 'Engineering',
    description: '2020-10-09',
  },
  {
    username: 'jonathan20',
    firstName: 'Nancy',
    lastName: 'Phillips',
    email: 'kimberlysilva@gmail.com',
    birthDate: '2003-12-15',
    basicSalary: 49096.99,
    status: 'On Leave',
    group: 'Marketing',
    description: '2021-07-20',
  },
  {
    username: 'michael58',
    firstName: 'John',
    lastName: 'Garrett',
    email: 'gonzalezashley@weiss-garrett.org',
    birthDate: '1978-07-23',
    basicSalary: 76877.69,
    status: 'Active',
    group: 'Engineering',
    description: '2021-02-15',
  },
  {
    username: 'ywilliams',
    firstName: 'Wendy',
    lastName: 'Boyer',
    email: 'hlowe@duran.biz',
    birthDate: '1984-01-02',
    basicSalary: 37061.65,
    status: 'Inactive',
    group: 'HR',
    description: '2021-11-09',
  },
  {
    username: 'sarah37',
    firstName: 'Catherine',
    lastName: 'Mitchell',
    email: 'aaron44@bonilla.com',
    birthDate: '2000-06-07',
    basicSalary: 91378.62,
    status: 'On Leave',
    group: 'Sales',
    description: '2024-02-06',
  },
  {
    username: 'jonesaudrey',
    firstName: 'Christian',
    lastName: 'Manning',
    email: 'joel28@blake.com',
    birthDate: '1979-09-04',
    basicSalary: 67686.99,
    status: 'Inactive',
    group: 'Engineering',
    description: '2023-04-10',
  },
  {
    username: 'travis22',
    firstName: 'Hailey',
    lastName: 'Mitchell',
    email: 'deborahstewart@yahoo.com',
    birthDate: '1966-06-24',
    basicSalary: 66429.8,
    status: 'On Leave',
    group: 'Engineering',
    description: '2021-10-31',
  },
  {
    username: 'dawsonmark',
    firstName: 'Carol',
    lastName: 'Porter',
    email: 'romerojonathan@hardy.com',
    birthDate: '2001-05-24',
    basicSalary: 31847.39,
    status: 'Active',
    group: 'HR',
    description: '2021-11-04',
  },
  {
    username: 'andersonbenjamin',
    firstName: 'Christian',
    lastName: 'Ross',
    email: 'ambermcguire@hotmail.com',
    birthDate: '1996-08-01',
    basicSalary: 69615.1,
    status: 'On Leave',
    group: 'HR',
    description: '2021-12-23',
  },
  {
    username: 'chenlinda',
    firstName: 'Jessica',
    lastName: 'Foster',
    email: 'calexander@wilson.com',
    birthDate: '1966-06-19',
    basicSalary: 43669.0,
    status: 'Inactive',
    group: 'Engineering',
    description: '2024-03-15',
  },
  {
    username: 'kblanchard',
    firstName: 'Daniel',
    lastName: 'Garcia',
    email: 'timothy62@hutchinson-camacho.com',
    birthDate: '1964-06-15',
    basicSalary: 84651.54,
    status: 'On Leave',
    group: 'Engineering',
    description: '2021-10-27',
  },
  {
    username: 'scott48',
    firstName: 'Douglas',
    lastName: 'Hunter',
    email: 'ethan87@monroe-wilkinson.net',
    birthDate: '1978-11-02',
    basicSalary: 43847.42,
    status: 'Active',
    group: 'Finance',
    description: '2022-11-21',
  },
  {
    username: 'qbradley',
    firstName: 'Diane',
    lastName: 'Miller',
    email: 'everetttiffany@foster-stone.org',
    birthDate: '1989-11-04',
    basicSalary: 89125.36,
    status: 'Active',
    group: 'Engineering',
    description: '2024-04-30',
  },
  {
    username: 'charlesholloway',
    firstName: 'Joe',
    lastName: 'Young',
    email: 'joseph96@fields-thomas.com',
    birthDate: '1994-05-01',
    basicSalary: 72984.87,
    status: 'Inactive',
    group: 'Marketing',
    description: '2020-10-24',
  },
  {
    username: 'collinball',
    firstName: 'Andrew',
    lastName: 'Fuller',
    email: 'watsonjoseph@gmail.com',
    birthDate: '1979-09-07',
    basicSalary: 108144.9,
    status: 'Active',
    group: 'HR',
    description: '2020-11-25',
  },
  {
    username: 'lisaarnold',
    firstName: 'Richard',
    lastName: 'Robertson',
    email: 'kelly20@cooper.info',
    birthDate: '1995-08-12',
    basicSalary: 115284.44,
    status: 'Active',
    group: 'Sales',
    description: '2020-12-09',
  },
];
